name: Make Deps

on:
  push:
    branches:
      master

jobs:
  build:
    name: Make Deps
    runs-on: [ubuntu-latest]
    steps:
    - name: Install Dependencies
      run: sudo apt-get install autoconf automake libtool yasm nasm tcl
    - name: Checkout Blender
      run: git clone https://git.blender.org/blender.git
    # - name: Make Blender Deps
    #   working-directory: ./blender
    #   run: make deps
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: Build
        path: ./
