name: Make Deps

on:
  push:
    branches:
      master

jobs:
  build:
    name: Make Deps
    runs-on: [ubuntu-latest]
    steps:
    - name: Checkout Blender
      run: git clone https://git.blender.org/blender.git
    - run: cd blender && make deps
